const resList = [
    {
      info: {
        id: "758539",
        name: "Subway",
        city: "16",
        slugs: {
          restaurant: "subway-shewalkar-garden-pratap-nagar",
        },
        cloudinaryImageId: "1ace5fa65eff3e1223feb696c956b38b",
        locality: "SHEWALKAR GARDEN",
        areaName: "Mate Square, Nagpur",
        costForTwo: "₹350 for two",
        cuisines: ["Salads", "Snacks", "Desserts", "Beverages"],
        avgRating: 4.2,
        feeDetails: {
          restaurantId: "758539",
          title: "Delivery Charge",
          amount: "0",
        },
        totalRatingsString: "100+",
        promoted: true,
        adTrackingId:
          "cid=9981583~p=1~eid=0000018c-8093-9adc-3245-adeb00d70161~srvts=1702964206300~56861",
        sla: {
          deliveryTime: 27,
          minDeliveryTime: 25,
          maxDeliveryTime: 30,
          serviceability: "SERVICEABLE",
          slaString: "25-30 MINS",
          lastMileTravelString: "4.4 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2023-12-20 03:00:00",
          opened: true,
        },
        badges: {},
        aggregatedDiscountInfoV3: {
          header: "40% OFF",
          subHeader: "UPTO ₹80",
        },
      },
    },
    {
      info: {
        id: "126960",
        name: "Faasos - Wraps, Rolls & Shawarma",
        city: "16",
        slugs: {
          restaurant: "faasos-uday-nagar-ayodhya-nagar",
        },
        cloudinaryImageId: "af33b81798b11deba338e94b7585d348",
        locality: "Uday Nagar",
        areaName: "Dighori",
        costForTwo: "₹200 for two",
        cuisines: [
          "Kebabs",
          "Fast Food",
          "Snacks",
          "North Indian",
          "American",
          "Healthy Food",
          "Desserts",
          "Beverages",
        ],
        avgRating: 4.4,
        feeDetails: {
          restaurantId: "126960",
          title: "Delivery Charge",
          amount: "0",
        },
        totalRatingsString: "10K+",
        promoted: true,
        adTrackingId:
          "cid=10006368~p=2~eid=0000018c-8093-9adc-3245-adec00d70205~srvts=1702964206300~56861",
        sla: {
          deliveryTime: 45,
          minDeliveryTime: 45,
          maxDeliveryTime: 50,
          serviceability: "SERVICEABLE",
          slaString: "45-50 MINS",
          lastMileTravelString: "8.4 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2023-12-19 23:59:00",
          opened: true,
        },
        badges: {},
        aggregatedDiscountInfoV3: {
          header: "15% OFF",
          subHeader: "ABOVE ₹1000",
          discountTag: "FLAT DEAL",
        },
      },
      analytics: {},
      cta: {},
    },
    {
      info: {
        id: "79542",
        name: "Domino's Pizza",
        city: "16",
        slugs: {
          restaurant: "dominos-pioneer-society-pratap-nagar",
        },
        cloudinaryImageId: "nyzxblwvr5ircdy77eht",
        locality: "Pioneer Society",
        areaName: "Hingna T Point",
        costForTwo: "₹400 for two",
        cuisines: ["Pizzas", "Italian", "Pastas", "Desserts"],
        avgRating: 4.4,
        feeDetails: {
          restaurantId: "79542",
          title: "Delivery Charge",
          amount: "0",
        },
        totalRatingsString: "1K+",
        sla: {
          deliveryTime: 47,
          minDeliveryTime: 45,
          maxDeliveryTime: 50,
          serviceability: "SERVICEABLE",
          slaString: "45-50 MINS",
          lastMileTravelString: "7.2 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2023-12-20 00:55:00",
          opened: true,
        },
        badges: {},
        aggregatedDiscountInfoV3: {
          header: "₹150 OFF",
          subHeader: "ABOVE ₹299",
          discountTag: "FLAT DEAL",
        },
      },
      analytics: {},
      cta: {},
    },
    {
      info: {
        id: "566227",
        name: "Faasos' Signature Wraps & Rolls",
        city: "16",
        slugs: {
          restaurant:
            "signature-wraps-rolls-by-faasos-azad-chowk-near-gandhi-chowk-sadar",
        },
        cloudinaryImageId: "c583ca6ce40b426797a78ae2ac91f2ec",
        locality: "Mohan Nagar",
        areaName: "Sadar",
        costForTwo: "₹350 for two",
        cuisines: [
          "Fast Food",
          "Snacks",
          "North Indian",
          "Desserts",
          "Beverages",
        ],
        avgRating: 4.3,
        feeDetails: {
          restaurantId: "566227",
          title: "Delivery Charge",
          amount: "0",
        },
        totalRatingsString: "100+",
        promoted: true,
        adTrackingId:
          "cid=10010037~p=3~eid=0000018c-8093-9adc-3245-aded00d70350~srvts=1702964206300~56861",
        sla: {
          deliveryTime: 34,
          minDeliveryTime: 30,
          maxDeliveryTime: 35,
          serviceability: "SERVICEABLE",
          slaString: "30-35 MINS",
          lastMileTravelString: "3.0 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2023-12-19 23:59:00",
          opened: true,
        },
        badges: {},
        aggregatedDiscountInfoV3: {
          header: "50% OFF",
          subHeader: "UPTO ₹100",
        },
      },
      analytics: {},
      cta: {},
    },
    {
      info: {
        id: "56321",
        name: "Shabana's Herbs & Spices",
        city: "16",
        slugs: {
          restaurant: "shabanas-herbes-spices-byramji-town-sadar",
        },
        cloudinaryImageId: "brcoac0lhked2uxqnfuz",
        locality: "Chhaoni",
        areaName: "Chhaoni",
        costForTwo: "₹300 for two",
        cuisines: ["Indian", "Chinese", "Continental", "Snacks"],
        avgRating: 4,
        feeDetails: {
          restaurantId: "56321",
          title: "Delivery Charge",
          amount: "0",
        },
        totalRatingsString: "10K+",
        sla: {
          deliveryTime: 44,
          minDeliveryTime: 40,
          maxDeliveryTime: 45,
          serviceability: "SERVICEABLE",
          slaString: "40-45 MINS",
          lastMileTravelString: "6.9 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2023-12-19 22:50:00",
          opened: true,
        },
        aggregatedDiscountInfo: {},
        badges: {},
        aggregatedDiscountInfoV2: {},
      },
      analytics: {},
      cta: {},
    },
    {
      info: {
        id: "63012",
        name: "LunchBox - Meals and Thalis",
        city: "16",
        slugs: {
          restaurant: "lunchbox-lake-view-appartment-t-point-hingna-pratap-nagar",
        },
        cloudinaryImageId: "y2qnmifzwza6zwxclgky",
        locality: "lake view Appartment, T point Hingna",
        areaName: "Trimurti Nagar",
        costForTwo: "₹200 for two",
        cuisines: [
          "Biryani",
          "North Indian",
          "Punjabi",
          "Healthy Food",
          "Desserts",
          "Beverages",
        ],
        avgRating: 4.3,
        feeDetails: {
          restaurantId: "63012",
          title: "Delivery Charge",
          amount: "0",
        },
        totalRatingsString: "5K+",
        promoted: true,
        adTrackingId:
          "cid=10006372~p=5~eid=0000018c-8093-9adc-3245-adef00d70549~srvts=1702964206300~56861",
        sla: {
          deliveryTime: 33,
          minDeliveryTime: 30,
          maxDeliveryTime: 35,
          serviceability: "SERVICEABLE",
          slaString: "30-35 MINS",
          lastMileTravelString: "5.7 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2023-12-19 23:59:00",
          opened: true,
        },
        badges: {},
        aggregatedDiscountInfoV3: {
          header: "ITEMS",
          subHeader: "AT ₹159",
        },
      },
      analytics: {},
      cta: {},
    },
    {
      info: {
        id: "54053",
        name: "Pizza Hut",
        city: "16",
        slugs: {
          restaurant: "pizza-hut-1st-flr-eternity-mall-variety-square-sitabuldi",
        },
        cloudinaryImageId: "2b4f62d606d1b2bfba9ba9e5386fabb7",
        locality: "Sitabuldi",
        areaName: "Sitabuldi",
        costForTwo: "₹300 for two",
        cuisines: ["Pizzas"],
        avgRating: 4.2,
        feeDetails: {
          restaurantId: "54053",
          title: "Delivery Charge",
          amount: "0",
        },
        totalRatingsString: "5K+",
        sla: {
          deliveryTime: 38,
          minDeliveryTime: 35,
          maxDeliveryTime: 40,
          serviceability: "SERVICEABLE",
          slaString: "35-40 MINS",
          lastMileTravelString: "1.4 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2023-12-19 23:00:00",
          opened: true,
        },
        badges: {},
        aggregatedDiscountInfoV3: {
          header: "50% OFF",
          subHeader: "UPTO ₹100",
        },
      },
      analytics: {},
      cta: {},
    },
    {
      info: {
        id: "510859",
        name: "Kwality Walls Frozen Dessert and Ice Cream Shop",
        city: "16",
        slugs: {
          restaurant:
            "kwality-walls-frozen-dessert-and-ice-cream-shop-wardha-road-wardha-road-3",
        },
        cloudinaryImageId: "owmnx4cmhygad1dtxxzw",
        locality: "Surendra Nagar",
        areaName: "Manish Nagar",
        costForTwo: "₹200 for two",
        cuisines: ["Desserts", "Ice Cream", "Ice Cream Cakes"],
        avgRating: 4.7,
        feeDetails: {
          restaurantId: "510859",
          title: "Delivery Charge",
          amount: "0",
        },
        totalRatingsString: "500+",
        promoted: true,
        adTrackingId:
          "cid=9929305~p=7~eid=0000018c-8093-9adc-3245-adf100d70703~srvts=1702964206300~56861",
        sla: {
          deliveryTime: 21,
          minDeliveryTime: 20,
          maxDeliveryTime: 25,
          serviceability: "SERVICEABLE",
          slaString: "20-25 MINS",
          lastMileTravelString: "2.8 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2023-12-19 23:59:00",
          opened: true,
        },
        badges: {},
        aggregatedDiscountInfoV3: {
          header: "50% OFF",
          subHeader: "UPTO ₹100",
        },
      },
      analytics: {},
      cta: {},
    },
    {
      info: {
        id: "333450",
        name: "Biryani By Kilo",
        city: "16",
        slugs: {
          restaurant: "biryani-by-kilo-dharampeth-dharampeth",
        },
        cloudinaryImageId: "bf9be1c6b9d796850f426281559cb2d2",
        locality: "Dharampeth",
        areaName: "Dharampeth",
        costForTwo: "₹499 for two",
        cuisines: [
          "Biryani",
          "Hyderabadi",
          "North Indian",
          "Kebabs",
          "Mughlai",
          "Desserts",
        ],
        avgRating: 4.3,
        feeDetails: {
          restaurantId: "333450",
          title: "Delivery Charge",
          amount: "0",
        },
        totalRatingsString: "1K+",
        promoted: true,
        adTrackingId:
          "cid=9656537~p=9~eid=0000018c-8093-9adc-3245-adf300d7096f~srvts=1702964206300~56861",
        sla: {
          deliveryTime: 52,
          minDeliveryTime: 50,
          maxDeliveryTime: 55,
          serviceability: "SERVICEABLE",
          slaString: "50-55 MINS",
          lastMileTravelString: "2.9 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2023-12-19 23:00:00",
          opened: true,
        },
        badges: {
          textExtendedBadges: [
            {
              iconId: "guiltfree/GF_Logo_android_3x",
              shortDescription: "options available",
              fontColor: "#7E808C",
            },
          ],
        },
        aggregatedDiscountInfoV3: {
          header: "20% OFF",
          subHeader: "UPTO ₹50",
        },
      },
    },
    {
      info: {
        id: "720356",
        name: "Wendy's Burgers",
        city: "16",
        slugs: {
          restaurant: "wendys-burgers-mohan-nagar-sadar",
        },
        cloudinaryImageId: "a2ec5418246b622ec4baa3bd051ef6ab",
        locality: "Mohan Nagar",
        areaName: "Sadar",
        costForTwo: "₹200 for two",
        cuisines: ["Burgers", "American", "Fast Food", "Snacks", "Beverages"],
        avgRating: 4.5,
        feeDetails: {
          restaurantId: "720356",
          title: "Delivery Charge",
          amount: "0",
        },
        totalRatingsString: "100+",
        sla: {
          deliveryTime: 33,
          minDeliveryTime: 30,
          maxDeliveryTime: 35,
          serviceability: "SERVICEABLE",
          slaString: "30-35 MINS",
          lastMileTravelString: "3.0 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2023-12-19 23:59:00",
          opened: true,
        },
        badges: {},
        aggregatedDiscountInfoV3: {
          header: "ITEMS",
          subHeader: "AT ₹129",
        },
      },
      analytics: {},
      cta: {},
    },
    {
      info: {
        id: "553826",
        name: "Starbucks Coffee",
        city: "16",
        slugs: {
          restaurant: "starbucks-coffee-dharampeth-bajaj-nagar",
        },
        cloudinaryImageId: "0c958153eeb436db6d515ca36e47e8a4",
        locality: "Garden Road",
        areaName: "Dharampeth",
        costForTwo: "₹400 for two",
        cuisines: [
          "Beverages",
          "Cafe",
          "Snacks",
          "Desserts",
          "Bakery",
          "Ice Cream",
        ],
        avgRating: 4.3,
        feeDetails: {
          restaurantId: "553826",
          title: "Delivery Charge",
          amount: "0",
        },
        totalRatingsString: "500+",
        promoted: true,
        adTrackingId:
          "cid=9953409~p=10~eid=0000018c-8093-9adc-3245-adf400d70a37~srvts=1702964206300~56861",
        sla: {
          deliveryTime: 21,
          minDeliveryTime: 20,
          maxDeliveryTime: 25,
          serviceability: "SERVICEABLE",
          slaString: "20-25 MINS",
          lastMileTravelString: "2.5 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2023-12-19 23:59:00",
          opened: true,
        },
        badges: {},
        aggregatedDiscountInfoV3: {
          header: "30% OFF",
          subHeader: "UPTO ₹75",
        },
      },
      analytics: {},
      cta: {},
    },
    {
      info: {
        id: "399053",
        name: "Barbeque",
        city: "16",
        slugs: {
          restaurant: "biryani-bazar-dharampeth-dharampeth",
        },
        cloudinaryImageId: "75990b7f56ec0f7fddf86346335ded00",
        locality: "Canal Road",
        areaName: "Gokulpeth",
        costForTwo: "₹200 for two",
        cuisines: ["Biryani", "Kebabs", "Indian", "Barbecue", "North Indian"],
        avgRating: 4.4,
        feeDetails: {
          restaurantId: "399053",
          title: "Delivery Charge",
          amount: "0",
        },
        totalRatingsString: "500+",
        sla: {
          deliveryTime: 27,
          minDeliveryTime: 25,
          maxDeliveryTime: 30,
          serviceability: "SERVICEABLE",
          slaString: "25-30 MINS",
          lastMileTravelString: "2.9 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2023-12-19 23:30:00",
          opened: true,
        },
        badges: {},
        aggregatedDiscountInfoV3: {
          header: "50% OFF",
          subHeader: "UPTO ₹100",
        },
      },
      analytics: {},
      cta: {},
    },
    {
      info: {
        id: "103399",
        name: "Biryani Plazza",
        city: "16",
        slugs: {
          restaurant: "biryani-plazza-hingna-road-pratap-nagar",
        },
        cloudinaryImageId: "glrtap1ive0bqa6lgnpu",
        locality: "Sumitra Market",
        areaName: "Hingna T Point",
        costForTwo: "₹250 for two",
        cuisines: ["Biryani", "North Indian", "Mughlai", "Indian"],
        avgRating: 4,
        feeDetails: {
          restaurantId: "103399",
          title: "Delivery Charge",
          amount: "0",
        },
        totalRatingsString: "1K+",
        sla: {
          deliveryTime: 50,
          minDeliveryTime: 45,
          maxDeliveryTime: 50,
          serviceability: "SERVICEABLE",
          slaString: "45-50 MINS",
          lastMileTravelString: "9.9 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2023-12-19 23:30:00",
          opened: true,
        },
        aggregatedDiscountInfo: {},
        badges: {},
        aggregatedDiscountInfoV2: {},
      },
      analytics: {},
      cta: {},
    },
    {
      info: {
        id: "503583",
        name: "Egg Break",
        city: "16",
        slugs: {
          restaurant: "egg-break-sadar-sadar",
        },
        cloudinaryImageId: "bqvjbj042wmrfqxpv09q",
        locality: "Jafar Nagar",
        areaName: "Mankapur",
        costForTwo: "₹150 for two",
        cuisines: ["Indian", "Fast Food", "Snacks", "Beverages"],
        avgRating: 4.2,
        feeDetails: {
          restaurantId: "503583",
          title: "Delivery Charge",
          amount: "0",
        },
        totalRatingsString: "50+",
        sla: {
          deliveryTime: 47,
          minDeliveryTime: 45,
          maxDeliveryTime: 50,
          serviceability: "SERVICEABLE",
          slaString: "45-50 MINS",
          lastMileTravelString: "6.9 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2023-12-19 23:00:00",
          opened: true,
        },
        aggregatedDiscountInfo: {},
        badges: {},
        aggregatedDiscountInfoV2: {},
      },
    },
  ];

  export default resList;